// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyzhulvzmbyhaviysonp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5emh1bHZ6bWJ5aGF2aXlzb25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTAyOTMsImV4cCI6MjA1NTQ4NjI5M30.HMAF834XB_hkxjQmWkoIgs6x2nJHEYFKwV47OVWMGsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);